# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4f3f664b14ee8e771b97a26f439108db66bd6a2cd5acaa23592ccd7aed700a08226d0db3607f8ab4f5df5a12bc2bd80637cc810c14bfc0bdcf51c6643f6f0ec

test:
  secret_key_base: 452aff3e3ecda4bb1c3e4af620b12bf925cd2f7d4a5328b3045075eb6635a24f41a621e367a059baa88703536eeff4f23211560c15fc9189be64c4a3bc0bdc5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
